services:
  - type: web
    name: exercise1-web-project
    runtime: python
    plan: free
    buildCommand: python -m pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend app:app
    healthCheckPath: /api/profiles